version: '3.7'

services:
  phpfpm:
    build: ./.docker-compose
    image: phpfpm-7.4:local
    restart: always
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx
    depends_on:
      - "phpfpm"
    volumes:
      - ./:/var/www/html
      - ./.docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"